---
title: "git_00"
author: "JOSE GUZMAN"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

The sun was shining on the sea,  
shining with all his might:   
He did his very best to make   
The billows smooth and bright   
And this was odd, because it was.  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
"It's very rude of him," she said,  
"To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

What was it like to love him? Asked gratitude.  
It was like being exhumed, I answered. And  
brought to life in a flash of brilliance.   

What was it like to be loved in return? Asked Joy.  
It was like being seen after a perpetual   darkness, I replied.  
To be heard after a life time of silence    

What was it like to lose him? Asked Sorrow.  
There was a long pause before I responded:  
It was like hearing every goodbye ever said.   
